

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL('https://next-seo-demo.onrender.com'),
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en-US',
      'de-DE': '/de-DE',
    },
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

      >
        {children}
      </body>
    </html>
  );
}
